# fly.toml

app = "music-analyzer-gay"
primary_region = "sin"

[build]

# This is the corrected health check section
[checks]
  [checks.alive_check]
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s" # Increased grace period slightly for safety
    method = "GET"
    path = "/login"
    protocol = "http"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "app_data"
  destination = "/data"