# fly.toml
app = "music-analyzer-gay"
primary_region = "sin"

[build]

[deploy]
  release_command = "/app/start.sh"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "app_data"
  destination = "/data"